# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'Ubuntu-Latest'
    steps:
    - task: Maven@4
      inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
                SourceFolder: '$(System.DefaultWorkingDirectory)'
                Contents: '**/target/*.?(war|jar)'
                TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop
    - task: Docker@2
      displayName: Build an image
      inputs:
            containerRegistry: 'docker'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            tags: '$(tag)'

- stage: deploy
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'Ubuntu-Latest'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'BFSI_LGI_DevOps_Training_POC (f3f0b402-1498-4537-9728-704a780011a0)'
        appName: 'arunsite'
